web:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab-ce
  restart: always
  hostname: 'gitlab'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
      external_url 'http://127.0.0.1'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '80:80'
    - '443:443'
    - '2224:22'
  volumes:
    - '$GITLAB_HOME/config:/etc/gitlab'
    - '$GITLAB_HOME/logs:/var/log/gitlab'
    - '$GITLAB_HOME/data:/var/opt/gitlab'
